# Generated by Django 5.2.8 on 2026-03-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cryptoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0)),
                ('signal', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('HOLD', 'HOLD')], max_length=10)),
                ('confidence', models.IntegerField()),
                ('target', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('ma_short', models.FloatField(blank=True, null=True)),
                ('ma_long', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
