# Generated by Django 5.2.8 on 2026-03-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptodata',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='target',
        ),
    ]
