# Generated by Django 5.2.8 on 2026-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_remove_cryptodata_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodata',
            name='signal',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('HOLD', 'HOLD')], max_length=50),
        ),
    ]
