# Generated by Django 5.2.8 on 2026-03-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_alter_cryptodata_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodata',
            name='decision',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
